name: EKS Infrastructure

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        default: 'plan'
        type: choice
        options:
        - plan
        - apply
        - destroy
  push:
    branches: [ main ]
    paths: ['**.tf', '**.tfvars']
  pull_request:
    branches: [ main ]
    paths: ['**.tf', '**.tfvars']

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  TF_VERSION: 1.5.0

jobs:
  vpc-ec2:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Terraform Format Check
      run: terraform fmt -check -recursive

    - name: Init & Validate VPC/EC2
      run: |
        terraform init
        terraform validate
      working-directory: ./vpc-ec2

    - name: Plan VPC/EC2
      if: github.event_name == 'pull_request' || github.event.inputs.action == 'plan'
      run: terraform plan -var-file=variables.tfvars
      working-directory: ./vpc-ec2

    - name: Apply VPC/EC2
      if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event.inputs.action == 'apply'
      run: terraform apply -auto-approve -var-file=variables.tfvars
      working-directory: ./vpc-ec2

  eks:
    runs-on: ubuntu-latest
    needs: vpc-ec2
    if: github.event.inputs.action != 'destroy'
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Setup Helm
      uses: azure/setup-helm@v4
      with:
        version: '3.12.0'

    - name: Init & Validate EKS
      run: |
        terraform init
        terraform validate
      working-directory: ./eks

    - name: Plan EKS
      if: github.event_name == 'pull_request' || github.event.inputs.action == 'plan'
      run: terraform plan -var-file=../variables.tfvars
      working-directory: ./eks

    - name: Apply EKS
      if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event.inputs.action == 'apply'
      run: terraform apply -auto-approve -var-file=../variables.tfvars
      working-directory: ./eks

    - name: Configure kubectl
      if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event.inputs.action == 'apply'
      run: |
        aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name eks-cluster
        kubectl get nodes

  destroy:
    runs-on: ubuntu-latest
    if: github.event.inputs.action == 'destroy'
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Init EKS
      run: terraform init
      working-directory: ./eks

    - name: Destroy EKS
      run: terraform destroy -auto-approve -var-file=../variables.tfvars
      working-directory: ./eks
      continue-on-error: true

    - name: Init VPC/EC2
      run: terraform init
      working-directory: ./vpc-ec2

    - name: Destroy VPC/EC2
      run: terraform destroy -auto-approve -var-file=variables.tfvars
      working-directory: ./vpc-ec2